### ISSUE TITLE
epmd port

### ISSUE THREAD

**Issue by rpavlovs** [erlio/docker-vernemq#15]
Hi,

I've noticed that Dockerfile is exposing port `4349` for `epmd`:
https://github.com/erlio/docker-vernemq/blob/master/Dockerfile#L36

At the same time, official doc mentions `4369`:
https://vernemq.com/docs/clustering/communication.html

Is that intended?

**Comment by dergraf** [comment]
You're right, Thanks. Can you create a PR?

**Comment by dergraf** [comment]
Is fixed, I also bumped the VerneMQ Version number.
