### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by RangerMauve** [erlio/docker-vernemq#2]
This is kinda cool to help people whet their whistle, but having authorization is pretty important. It probably would be as simple as letting users mount a volume containing an `acl` file as described [here](https://vernemq.com/docs/configuration/authorization.html)

**Comment by dergraf** [comment]
Great feedback, thanks.
How about mounting the vmq.acl and vmq.passwd files into the /etc/vernemq folder?

**Comment by RangerMauve** [comment]
Yeah, I think that would make sense

**Comment by larshesel** [comment]
Closing this as a working solutions was proposed.
