### ISSUE TITLE
Unable to set nodename

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/docker-vernemq#23]
Unable to set nodename for vernemq node in docker container.

After looking at bin/vernemq.sh, I feel the issues to be in bin/vernemq.sh line 10. Below could be the possible fix.
`if env | grep -q "DOCKER_VERNEMQ_NODENAME"; then`
`    sed -i.bak "s/VerneMQ@${DOCKER_VERNEMQ_NODENAME}/" /etc/vernemq/vm.args`
`else`
`    sed -i.bak "s/VerneMQ@127.0.0.1/VerneMQ@${IP_ADDRESS}/" /etc/vernemq/vm.args`

Or I might have misunderstood.

Can someone help me with this issue?

**Comment by ioolkos** [comment]
@vedavidhbudimuri thanks... I'm not sure I understand. What shows you that you cannot configure the nodename?

**Comment by vedavidhbudimuri** [comment]
while running the docker container in interactive mode I could see logs saying something like this 
`2017-08-04 15:04:48.722 [info] <0.31.0> Application vmq_plugin started on node 'VerneMQ@172.18.0.5'` 

Which isn't the one I have assigned, So I assumed that there might be some issue with the image or with the way I'm starting the docker.

**Comment by dergraf** [comment]
Your changes in the script are wrong!

For a proper replacement using sed you should use 

     sed -i.bak "s/VerneMQ@127.0.0.1/VerneMQ@${DOCKER_VERNEMQ_NODENAME}/" /etc/vernemq/vm.args

**Comment by vedavidhbudimuri** [comment]
Oops !!! I missed it. 
Can I know when these changes will reflect?

So this is the possible fix right?
`if env | grep -q "DOCKER_VERNEMQ_NODENAME"; then`
`sed -i.bak "s/VerneMQ@127.0.0.1/VerneMQ@${DOCKER_VERNEMQ_NODENAME}/" /etc/vernemq/vm.args`
`else`
`sed -i.bak "s/VerneMQ@127.0.0.1/VerneMQ@${IP_ADDRESS}/" /etc/vernemq/vm.args`

**Comment by dergraf** [comment]
I am happy to merge your PR

**Comment by vedavidhbudimuri** [comment]
Hey @dergraf,  I have added a pull request (#24).
