### ISSUE TITLE
Passing config arguments retuns an error

### ISSUE THREAD

**Issue by svh1985** [erlio/docker-vernemq#27]
Hi,

When I run the container with the port mapping argument and the anonymous argument I get the following error;
```
❯ docker run --name vernemq1 -d erlio/docker-vernemq -p 1883:1883 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
7adb4137d8258032d1e9e6d35cb25b6682723896bd6bac3c8627fbdc2e2cd42e
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"-p\": executable file not found in $PATH".
```

When I remove the -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" argument it successfully starts but it isn't reachable because I'm running it on a Mac

Cheers!

**Comment by jeremylink** [comment]
Not sure of the rules, but I think if you move the '-d erlio/docker-vernemq' to the end of the line it will work for you.
