### ISSUE TITLE
ACL patterns for anonymous clients are applied to all clients

### ISSUE THREAD

**Issue by jeremylink** [erlio/docker-vernemq#28]
The docs for the ACL file state that the first set of topics (before a user is defined) are applied to anonymous clients, but I find that it applies to ALL clients (I have anonymous clients disabled).

**Comment by dergraf** [comment]
Maybe this is wrong in the docs.. They apply to all clients, vmq_acl doesn't distinguish between users authenticated anonymously or the ones authenticated via a plugin e.g. vmq_passwd. 

We'll check the docs accordingly.
