### ISSUE TITLE
File Based Authentication not working with ENV variables

### ISSUE THREAD

**Issue by perotom** [erlio/docker-vernemq#29]
I get the following error when i try to pass users like that:

`DOCKER_VERNEMQ_USER_HW='password'`

`/usr/sbin/start_vernemq: line 23: [: DOCKER_VERNEMQ_USER_HW='password': binary operator expected
`

Probably caused by: 
https://github.com/erlio/docker-vernemq/blob/4176dff5e20728ce482a65281aa3b561e6c45965/bin/vernemq.sh#L23

**Comment by cah-calixtomelean** [comment]
Yeah, that's annoying. It actually gets passed that. The actual issue is:

vmq-passwd -c /etc/vernemq/vmq.passwd $username <<EOF

The "-c" tells vmq-passwd to create a new password file; so the result is only one user in the file

**Comment by perotom** [comment]
I think it is an easy fix but otherwise the docker images is useless for me.

**Comment by larshesel** [comment]
If you know how to solve the problem a PR would be awesome!

**Comment by perotom** [comment]
I haven't tested the solution but should work.

**Comment by larshesel** [comment]
Thanks for the contribution!
