### ISSUE TITLE
Multiple ip breaks startup script

### ISSUE THREAD

**Issue by alex88** [erlio/docker-vernemq#3]
I'm trying to launch a vernemq instance in a rancher environment, I get:

```
8/30/2016 12:05:53 PM/usr/sbin/start_vernemq: line 49: [: -ne: unary operator expected
8/30/2016 12:06:19 PMvernemq failed to start within 15 seconds,
8/30/2016 12:06:19 PMsee the output of 'vernemq console' for more information.
8/30/2016 12:06:19 PMIf you want to wait longer, set the environment variable
8/30/2016 12:06:19 PMWAIT_FOR_ERLANG to the number of seconds to wait.
```

`vernemq console` throws an exception saying there's a syntax error at these lines:

```
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.17.0.17
10.42.0.193:1883
listener.ws.default = 172.17.0.17
10.42.0.193:8080
listener.vmq.clustering = 172.17.0.17
10.42.0.193:44053
listener.http.metrics = 172.17.0.17
```

could be that with multiple ip they go on a newline?

**Comment by ioolkos** [comment]
Hi @alex88 
Thanks for reporting!

You should not configure multiple brokers in one vernemq.conf. And if you need multiple listeners, then all should be configured under a different name (listener.tcp.myname1, listener.tcp.myname2 etc)

I hope this helps.

@dergraf I don't really know Rancher; correct me if I speak nonsense. Also: we need to update docker-vernemq to 0.14.1 one of these days.

**Comment by alex88** [comment]
@ioolkos just another docker orchestration tool, basically the problem happens anytime you have multiple ips and it's happening because https://github.com/erlio/docker-vernemq/blob/master/bin/vernemq.sh#L3 returns multiple lines.

Maybe would be better to read only the first line?

**Comment by ioolkos** [comment]
Ah, sorry, my confusion. It looks up the IP adresses and then automatically (and incorrectly) writes to vernemq.conf trying to configure listeners.
So there is the wrong assumption in the script, that a network interface only has 1 IP address?
cc/ @dergraf what can we do?

**Comment by alex88** [comment]
Another (more complex) option would be to setup multiple listeners with a loop:

```
listener.tcp.default = 172.17.0.17:1883
listener.tcp.default2 = 10.42.0.193:1883
listener.ws.default = 172.17.0.17:8080
listener.ws.default2 = 10.42.0.193:8080
```

and so on

**Comment by dergraf** [comment]
Would it be a solution to listen on 0.0.0.0?

**Comment by ioolkos** [comment]
In any case, don't hesitate to shoot a pull request @alex88 if you have something working for you.
