### ISSUE TITLE
vernemq.conf overwritten each restart

### ISSUE THREAD

**Issue by tho-wa** [erlio/docker-vernemq#42]
When I create docker container using docker run -p 1883:1883 -p 8080:8080 --name vernemq1 --restart=always  -v /data/vernemq/:/etc/vernemq/ -d erlio/docker-vernemq
the vernemq.conf seems to be overwritten each restart.
Can this behaviour be changed to keep the modifications?

**Comment by dergraf** [comment]
Hi,
thanks for reporting!

if you need this behaviour we recommend to use a separate volume and mount your own configuration file to `/etc/vernemq/vernemq.conf`.
