### ISSUE TITLE
The change using 'MY_POD_NAME' for "Automated clustering on Kubernetes" have not been reflected to README yet.

### ISSUE THREAD

**Issue by nmatsui** [erlio/docker-vernemq#44]
From  [commit f70257e](https://github.com/nmatsui/docker-vernemq/commit/f70257e636b2cabdfa3989af3b3c1c03d29fb951), the "Automated clustering on Kubernetes" requires 'MY_POD_NAME' instead of 'MY_POD_IP'.
But README has not been reflected this change yet.

**Comment by larshesel** [comment]
Good catch! Would it be possible to make a PR for this? I'd gladly merge it!

**Comment by nmatsui** [comment]
I send Pull Request https://github.com/erlio/docker-vernemq/pull/45
Please check this!
