### ISSUE TITLE
Unable to set bind address for listeners

### ISSUE THREAD

**Issue by theasp** [erlio/docker-vernemq#48]
Hello, 

Currently the VerneMQ docker container determines the IP address of the container using this method:
```bash
IP_ADDRESS=$(ip -4 addr show eth0 | grep -oP "(?<=inet).*(?=/)"| sed -e "s/^[[:space:]]*//" | tail -n 1)
```

In my case, I want to run VerneMQ on multiple docker networks:
```
root@mqtt:/# ip -4 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
5365: eth0@if5366: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.17.0.26/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
5367: eth1@if5368: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.18.0.15/16 brd 172.18.255.255 scope global eth1
       valid_lft forever preferred_lft forever
5369: eth2@if5370: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.28.0.2/16 brd 172.28.255.255 scope global eth2
       valid_lft forever preferred_lft forever
```

I want it to answer on them all, so I would like to use `0.0.0.0` for the following, but there seems no way to accomplish this.  Setting the environment variables results in the generated lines added to the file before the auto-generated lines.
```bash
echo "listener.tcp.default = ${IP_ADDRESS}:1883" >> /etc/vernemq/vernemq.conf
echo "listener.ws.default = ${IP_ADDRESS}:8080" >> /etc/vernemq/vernemq.conf
echo "listener.vmq.clustering = ${IP_ADDRESS}:44053" >> /etc/vernemq/vernemq.conf
echo "listener.http.metrics = ${IP_ADDRESS}:8888" >> /etc/vernemq/vernemq.conf
```

Mounting the config file still results in the start script modifying it.  Perhaps the start script could look for vernemq.conf.local, and use that if it is present?  This seems to be a solution #42 as well.  I could do a PR for this if you like.

**Comment by ioolkos** [comment]
@theasp thanks! If it solves your problem, I'd welcome a PR with the vernemq.conf.local idea.
@larshesel, @dergraf does this make sense, or is there a simpler solution?

**Comment by dergraf** [comment]
yeah this would simplify things for the MQTT[S/WS] listeners. However for the clustering to work we need a specific IP for the vmq listener.
