### ISSUE TITLE
Use stdout logging instead of tailing the console.log file

### ISSUE THREAD

**Issue by codeadict** [erlio/docker-vernemq#55]
The `console.log` file gets rotated and can grow significantly to the point of making the service deployed using Docker vulnerable to interruptions due to full hard disk. I have experienced this issue in a production environment in AWS and will submit a fix for it once I sort it out and test it.

**Comment by dergraf** [comment]
good finding... maybe disabling file logging and only log to console could help

**Comment by codeadict** [comment]
Yep, that and not running VerneMQ in the background so you can still use `docker logs CONTAINER_ID`

**Comment by codeadict** [comment]
PR submitted

**Comment by codeadict** [comment]
This can be closed now
