### ISSUE TITLE
Excessive memory consuption, too many os proceses ?

### ISSUE THREAD

**Issue by siscia** [erlio/docker-vernemq#6]
Hi,

I am seeing this strange beaviour from vernemq while running it under docker-compose.

![screenshot from 2016-10-27 14-27-25](https://cloud.githubusercontent.com/assets/640555/19767127/a1d792aa-9c51-11e6-97a6-22da27061b89.png)

There are A LOT, like tree maybe four htop's pages full of vernemq process (like os process, I guess, not erlang process).

Is this expected?
I stop and restart docker compose pretty ofter, may it be left from the old runs?

Cheers and congrats for the work,

Simone

**Comment by ioolkos** [comment]
Hi @siscia thanks! :)
I think those should be threads. I think there's an option in htop to not show that, forgot what it is though.

**Comment by siscia** [comment]
Hi @ioolkos !

Yes you are right, those are threads.

Pressing F5 show the tree in htop and show me something like this.

![screenshot from 2016-10-27 15-03-34](https://cloud.githubusercontent.com/assets/640555/19768180/b99c2ef0-9c56-11e6-8c91-e3794cf11f75.png)

Is this expected? Everything is working as it should? 

It using a little less than 400MB of RAM

**Comment by ioolkos** [comment]
This looks good, yes.

**Comment by siscia** [comment]
Great, I am closing so.

Just one question and you may also simply point me to some resource: why you spawn more os threads? How you are using? What they give you more than the default erlang processes?

**Comment by larshesel** [comment]
Hi @siscia. Erlang uses threads to avoid that IO operations block the erlang VM (see the `+A` flag here: http://erlang.org/doc/man/erl.html). In VerneMQ this value is by default 64. A higher value will give the erlang vm the ability to handle more concurrent IO - to find an optimal setting you'd have to measure performance for the use case at hand.
