### ISSUE TITLE
Binding metrics listener on 0.0.0.0

### ISSUE THREAD

**Issue by weeco** [erlio/docker-vernemq#68]
Hello,
whenever I bind 
```
listener.http.default = 127.0.0.1:8888
```

on `0.0.0.0:8888` I can not do a port-forward with kubernetes as Kubernetes indicates there is no socket listening on this port:

> E0918 15:28:31.681107   94370 portforward.go:331] an error occurred forwarding 8888 -> 8888: error forwarding port 8888 to pod eeb4904d4f112b65b78170d1c65f2251fbf4acc587ce7428de5239d2512bf041, uid : exit status 1: 2018/09/18 13:28:31 socat[1675256] E connect(5, AF=2 127.0.0.1:8888, 16): Connection refused
> E0918 15:28:31.691713   94370 portforward.go:331] an error occurred forwarding 8888 -> 8888: error forwarding port 8888 to pod eeb4904d4f112b65b78170d1c65f2251fbf4acc587ce7428de5239d2512bf041, uid : exit status 1: 2018/09/18 13:28:31 socat[1675257] E connect(5, AF=2 127.0.0.1:8888, 16): Connection refused

What's the reason for this behaviour? When I bind it on localhost instead it works as intended. I bound all my TCP sockets on 0.0.0.0 which is working as expected.

**Comment by dergraf** [comment]
Hello @weeco 

If I understood your question correctly you create a listener with `0.0.0.0:8888` ... right?
Would it work with a different port number?

**Comment by weeco** [comment]
Yes you understood it correctly. I haven't tried a different port number but just 0.0.0.0 and 127.0.0.1 as IP address. It did work with 127.0.0.1 as listener.

**Comment by weeco** [comment]
Figured it out. It happens because the listener is overwritten in the vernemq start script. I removed that line for my docker image and now it does work.
