### ISSUE TITLE
Push tag 0.15.2 on dockerhub

### ISSUE THREAD

**Issue by siscia** [erlio/docker-vernemq#9]

**Comment by chrisns** [comment]
appears to have been done though we're now at `0.15.3` as per the repo, but the image on dockerhub is `0.15.2` appears something weird has gone on with the automated build / webhooks in dockerhub?

**Comment by chrisns** [comment]
scrap that, `0.15.3` has been pushed, but its not `latest` :(

**Comment by siscia** [comment]
Great :+1:  I am honestly against the `latest` tag.

Feel free to close the issues or keep it open if you need a reminder :)

Cheers,

**Comment by dergraf** [comment]
Yeah, using latest is dangerous, but some people aren't afraid of anything! ;)

I close this, as 0.15.3 supersedes 0.15.2 anyways.
